jumpapplet: load_path breaks without an earlier config file
When starting jumpapplet without an earlier config file, it raises an UnboundLocalError

tparker@shostakovich:[~/data/src/autojump] ./jumpapplet
loading settings
no config file
Traceback (most recent call last):
  File "./jumpapplet", line 93, in popup
    paths=load_paths(maxpath=defaults["maxpath"])
  File "./jumpapplet", line 54, in load_paths
    path_dict=path_dict.items()
UnboundLocalError: local variable 'path_dict' referenced before assignment

This patch fixes that

Signed-off-by: Pierre Gueth <georges.wbushjr@laposte.net>